# Generated by Django 6.0.1 on 2026-01-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='satus',
            new_name='staus',
        ),
    ]
