# Generated by Django 6.0.1 on 2026-01-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_satus_blog_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='staus',
            new_name='status',
        ),
    ]
